name: Deploy

on:
  push:
    branches:
      - "master"

permissions:
  contents: write  # Для checkout
  pages: write    # Для Pages (если нужно)
  id-token: write # Для Pages (если нужно)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
       node-version: '18'

    - name: Generate package-lock.json и dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      env:
        VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      with:
        branch: gh-pages
        folder: dist
        token: ${{ secrets.GITHUB_TOKEN }}  # ← Добавь эту строку
